mongodb:
  host: mongodb://localhost:27017/dev
openAPI:
  info:
    license:
      name: ISC
      url: http://localhost:3500/api-template/license
    termsOfService: http://localhost:3500/api-template/terms
    contact:
      name: API Support
      email: support@devlambda.com
      url: http://localhost:3500/api-template/support
  externalDocs:
    description: Full documentation site
    url: http://localhost:3500/api-template/